#!/bin/bash

# If you are having trouble with this, make sure you have journal permissioms:
# sudo usermod -a -G systemd-journal USERNAME

# "-o cat" hides the redundant journal timestamp

journalctl -f -u pyhkd.service --since "6 hours ago" -o cat | grep -i --line-buffered 'error\|warn' | ccze -m ansi

